name: first-workflow
on: workflow_dispatch
  #push:
   # branches:
    #  - main
jobs:

    setup:
      runs-on: ubuntu-latest
      steps:
       -
          name: echo
          run: |
            echo 'hi there'
            ls -l
            
   
