name: sometrytry
on: workflow_dispatch
  #push:
   # branches:
    #  - main
jobs:

    setup:
      runs-on: ubuntu-latest
      steps:
       -
         uses: actions/checkout@v1
         
       -
          
          name: echo
          run: |
            ls -l
            echo 'hi there'
            
   
